language: go

go:
  - 1.11.x

before_install:
  # install ffmpeg
  - sudo add-apt-repository ppa:mc3man/trusty-media && sudo apt-get -qq update && sudo apt-get install -y ffmpeg

install:
  - go get -t ./...

script:
  - go vet ./...
  - go test ./...
  - go build
