language: go

dist: xenial

go:
  - 1.11.x

addons:
  apt:
    sources:
      - ppa:jonathonf/ffmpeg-4
    packages:
      - ffmpeg

install:
  - go get -t ./...

script:
  - go vet ./...
  - go test ./...
  - go build
